Transform: AWS::Serverless-2016-10-31
Description: lambdas
Globals:
  Function:
    Timeout: 20
Resources:
  WarhammerDiscordBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WarhammerDiscordBot/hello_world/
      Runtime: python3.11
      Handler: app.lambda_handler
      Description: WarhammerDiscordBot
      Events:
          WarhammerDiscordBot:
             Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
             Properties:
                Path: /WarhammerDiscordBot
                Method: get
Outputs:
# ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
# Find out more about other implicit resources you can reference within SAM
# https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WarhammerDiscordBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/WarhammerDiscordBot/"
  WarhammerDiscordBotFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt WarhammerDiscordBotFunction.Arn
  WarhammerDiscordBotFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt WarhammerDiscordBotFunctionRole.Arn